### ISSUE TITLE
The file is not signed and there are no hashsums

### ISSUE THREAD

**Issue by johnnynoone** [luckyrat/KeePass-Favicon-Downloader#7]
There should be a way to verify integrity of KeePassFaviconDownloader.plgx . SourceForge uses plain HTTP, so someone might tamper with the file while it's in transit.

You can publish hashes here on github. It would be even better if you signed the hashes with PGP. :)

**Comment by luckyrat** [comment]
You can check the hashes on Sourceforge (via HTTPS): https://sourceforge.net/projects/keepass-favicon/files/1.8.0/

Just click on the "i" icon on the file you're downloading and then compare with the file you have downloaded.

**Comment by johnnynoone** [comment]
Oh, I didn't knew that. Thanks. :)
